### PR TITLE
Parse timestamp columns in text format. Fixes vapor/mysql-nio#71

### LINKED ISSUE #71: Exception when reading MySQLTime formatted as text
### Describe the bug

The getter for MySQLData.time assumes the data is in .binary format. However, MariaDB 10.5 returns data from timestamp fields in .text format "2008-12-29 12:59:59", which leads to a fatal error unwrapping nil.

### To Reproduce

1. Run a Docker container with mariadb:10.5 and these command-line arguments:
    - --max-allowed-packet=512M
    - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    - --default-time-zone=America/New_York
2. Query the MariaDB server with:

```swift
let rows = try db.simpleQuery("SELECT CURRENT_TIMESTAMP();").wait()
print(rows)
```

### Expected behavior

The current timestamp should be returned. Instead, there is a fatal error at MySQLData.swift:458. 

### Environment

framework: 4.55.0
toolbox: 18.3.3
OS version: macOS 12.2.1

### Additional context

I think the fix is straightforward, and I hope to have a pull request to fix the problem soon.

### PR DESCRIPTION
**Pull request by samalone**
Add support for reading timestamp columns in text format.

Fixes #71

### CODE REVIEW

File: Tests/MySQLNIOTests/MySQLNIOTests.swift [hunk 1]
```diff
@@ -636,6 +636,19 @@ final class MySQLNIOTests: XCTestCase {
         XCTAssertEqual(time.date, nil)
     }
     
+    func testTextMySQLTimeParse() throws {
+        let conn = try MySQLConnection.test(on: self.eventLoop).wait()
+        defer { try! conn.close().wait() }
+        
+        // MariaDB 10.5 returns timestamp columns in text format.
```
Comment (gwynne) [inline Tests/MySQLNIOTests/MySQLNIOTests.swift:643]: More precisely, `simpleQuery()` uses the old text resultset protocol, which always returns textual results; it's not just MariaDB.
```suggestion
        // The text protocol returns timestamp columns in text format.
```

File: Tests/MySQLNIOTests/MySQLNIOTests.swift [hunk 2]
```diff
@@ -636,6 +636,19 @@ final class MySQLNIOTests: XCTestCase {
...
+        // Ensure these can be converted to MySQLTime without error.
+        let rows = try! conn.simpleQuery("SELECT CURRENT_TIMESTAMP() AS foo").wait()
```
Comment (gwynne) [inline Tests/MySQLNIOTests/MySQLNIOTests.swift:645]:
```suggestion
        let rows = try conn.simpleQuery("SELECT CURRENT_TIMESTAMP() AS foo").wait()
```

File: Tests/MySQLNIOTests/MySQLNIOTests.swift [hunk 3]
```diff
@@ -636,6 +636,19 @@ final class MySQLNIOTests: XCTestCase {
...
+        guard let _ = rows[0].column("foo")?.time else {
+            XCTFail("Could not convert to time: \(rows[0])")
+            return
+        }
```
Comment (gwynne) [inline Tests/MySQLNIOTests/MySQLNIOTests.swift:649]:
```suggestion
        XCTAssertNotNil(rows[0].column("foo")?.time)
```

**Comment by gwynne** [comment]
The problem with the tests will be fixed by the merge of #127

**Review by gwynne — APPROVED** [review]
